const className=`
bg-primary
bg-primary_disabled
bg-secondary
bg-secondary_disabled
hover:bg-primary_hover
focus:bg-primary_hover
active:bg-primary_active
border-green_text
border-blue_text
border-red_text
bg-red
bg-green
bg-blue
bg-yellow
hover:bg-red
hover:bg-green
focus-visible:bg-red
focus-visible:bg-green
hover:text-red_text
hover:text-green_text
focus-visible:bg-primary_hover
focus-visible:bg-secondary_hover
focus-visible:text-red_text
focus-visible:text-green_text
 disabled:bg-primary_disabled
  disabled:bg-secondary_disabled
`