const className=`
bg-primary
bg-primary_disabled
bg-secondary
bg-secondary_disabled
hover:bg-primary_hover
focus:bg-primary_hover
active:bg-primary_active
border-green_text
border-blue_text
border-red_text
bg-red
bg-green
bg-blue
bg-yellow
hover:bg-red
hover:bg-green
focus-active:bg-red
focus-active:bg-green
hover:text-red_text
hover:text-green_text
focus-active:text-red_text
focus-active:text-green_text
`